# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41ed352a589546e449553052d00e4f67e59f3aa758a9af3efcd53334ffec12cf35cbb5fc47a1d3362b3bedf3ed87d9cd2b87d16857489be1dcd05ba93cba2ff5

test:
  secret_key_base: cada36fbfc5b1206a0fc2a9e395162ddde9a3830762e1b5168af2ce0c6a418be86971b7bd494bc0336aa1e3dfa8762ae98e73dcf450ba4af043e823d0ae720a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
